GET http://127.0.0.1:3000/api/users HTTP/1.1

###

POST http://127.0.0.1:3000/api/users HTTP/1.1
content-type: application/json

{
    "username": "Bobber",
    "password": "Jelszo232323"
}

###

POST http://127.0.0.1:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "username": "Bobber23",
    "password": "1234"
}

###

GET http://127.0.0.1:3000/api/draftrewards HTTP/1.1
