
GET http://127.0.0.1:3000/api/draftselectedplayers HTTP/1.1

###

POST http://127.0.0.1:3000/api/draftselectedplayers HTTP/1.1
content-type: application/json

{
    "player": ""
}

###

GET http://127.0.0.1:3000/api/randomst HTTP/1.1

